### PR TITLE
Reward module init patch #1

### PR DESCRIPTION
**Pull request by rxRibo**
I leave this open for checking {patch #1 reward module]
Let me know for addition - </>

### CODE REVIEW

**Comment by RXbenjoZork** [comment]
rxDrinez look into this , 

thanks Ribo

**Comment by RXbenjoZork** [comment]
can you compile it?

**Comment by rxRibo** [comment]
Compiling Now will let you know in 5min, btw ill share something on discord chat.
please check it.

**Comment by rxDrinez** [comment]
compiling on my end. Let me know Ribo

**Pull request merged**
