### PR TITLE
Mn ladderized Initial Code

### PR DESCRIPTION
**Pull request by rxDrinez**
Tag to RX | BenjoZork - Review Before Merge

Test Code : 77774291BdgaUSUU

Commit Change Log to Main Branch of this Fork

### CODE REVIEW

**Comment by RXbenjoZork** [comment]
Looking to it please ask Ribo to get this test code too. Or fork your mnladderized code to initiate code testings

**Comment by RXbenjoZork** [comment]
**REVIEW THIS LINE**

while (it != mapFinalizedBudgets.end()) {
           CFinalizedBudget* pfinalizedBudget = &((*it).second);
           if (pfinalizedBudget->GetVoteCount() > nHighestCount &&
               nBlockHeight >= pfinalizedBudget->GetBlockStart() &&
               nBlockHeight <= pfinalizedBudget->GetBlockEnd()) {
               nHighestCount = pfinalizedBudget->GetVoteCount();
               
               
          -> GetBlockStart() && to GetBlockStart (80001) &&

**Comment by rxDrinez** [comment]
Thanks Benjo, 

and This line // nBlockHeight <= pfinalizedBudget->GetBlockEnd()) {

Will it affect the initial block?

**Comment by RXbenjoZork** [comment]
It wont affect we should leave that as it is on the test branch

This >>>>> to std::object

TrxValidationStatus transactionStatus = TrxValidationStatus::Invalid;
       int nHighestCount = 0;
       int nFivePercent = mnodeman.CountEnabled(ActiveProtocol()) / 20;
       std::vector<CFinalizedBudget*> ret;

**Comment by rxDrinez** [comment]
Got it! Fixing code on next commit after this

**Comment by RXbenjoZork** [comment]
Great! will merge and close now.
start working on rewards

**Review by RXbenjoZork — COMMENTED** [review]
Merge - approved

**Pull request merged**
